### ISSUE TITLE
importname obviously unhappens previous importname

### ISSUE THREAD

**Issue by befranz** [handshake-org/hsd#595] opened 2021-04-17 11:28 UTC
I tried to import bid data of several names from the same block or which have overlapping bidding blocks, it seems the last importname always 'wipes' bid data from imported name before.

Let's take brownsberger and harloff which were opened both at block 63700, data of brownsberger appears in Bob for example after I called 

hsw-rpc importname brownsberger 63699

but after doing the same with harloff, brownsberger's data is no longer available.

**Comment by Anunayj** [comment] 2021-04-21 12:39
Hmmm I was not really able to reproduce the issue you said, did you wait a few seconds for the wallet to finish rescanning before attempting `getauctioninfo`?

**Comment by pinheadmz** [comment] 2021-05-24 17:22
I also can not reproduce this issue in hsd.

I used two names opened in the same TX in the same block: https://blockexplorer.com/txs/15a92ff016c94fd7a04743377c09f6ff8cf35e035c9d02eec7541088cf383a1c

chain is synced.

```
--> hsd-cli info | jq .chain.progress
1
--> hsd-cli info | jq .chain.height
69139
```

Wallet has no state for either name

```
--> hsw-rpc getnameinfo btcpractice
Auction not found.
--> hsw-rpc getnameinfo btcproduction
Auction not found.
```

import first name, state exists for first name only

```
--> hsw-rpc importname btcpractice 69000
null
--> hsw-rpc getnameinfo btcpractice
{
  "name": "btcpractice",
  "nameHash": "2431a0223bb9a363cacddbc1505c7bb24503651cd75b34b07afbaf34970124be",
  "state": "BIDDING",
  "height": 69001,
  "renewal": 69001,
  "owner": {
    "hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "index": 4294967295
  },
  "value": 0,
  "highest": 0,
  "data": "",
  "transfer": 0,
  "revoked": 0,
  "claimed": 0,
  "renewals": 0,
  "registered": false,
  "expired": false,
  "weak": false,
  "stats": {
    "bidPeriodStart": 69038,
    "bidPeriodEnd": 69758,
    "blocksUntilReveal": 619,
    "hoursUntilReveal": 103.17
  }
}
--> hsw-rpc getnameinfo btcproduction
Auction not found.
--> hsw-rpc getbids btcpractice
[
  {
    "name": "btcpractice",
    "nameHash": "2431a0223bb9a363cacddbc1505c7bb24503651cd75b34b07afbaf34970124be",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 36
    },
    "lockup": 5110000,
    "blind": "06757269fc896b3caff0e92055bd15e14e45f15911d90b50703e6f930844b118",
    "own": false
  }
]
--> hsw-rpc getbids btcproduction
[]
```

import second name, wallet has state for both names

```
--> hsw-rpc importname btcproduction 69000
null
--> hsw-rpc getbids btcproduction
[
  {
    "name": "btcproduction",
    "nameHash": "b27dd9c0336e1db21fd0f4b8a989c3bfef4cca3ddc31b02f7b48f2c4e23d400a",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 21
    },
    "lockup": 5110000,
    "blind": "db1656bddfd25c07264f2f05407a488d28ca922518c85da414d2bff8163f054d",
    "own": false
  }
]
--> hsw-rpc getbids btcpractice
[
  {
    "name": "btcpractice",
    "nameHash": "2431a0223bb9a363cacddbc1505c7bb24503651cd75b34b07afbaf34970124be",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 36
    },
    "lockup": 5110000,
    "blind": "06757269fc896b3caff0e92055bd15e14e45f15911d90b50703e6f930844b118",
    "own": false
  }
]
--> hsw-rpc getnameinfo btcproduction
{
  "name": "btcproduction",
  "nameHash": "b27dd9c0336e1db21fd0f4b8a989c3bfef4cca3ddc31b02f7b48f2c4e23d400a",
  "state": "BIDDING",
  "height": 69001,
  "renewal": 69001,
  "owner": {
    "hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "index": 4294967295
  },
  "value": 0,
  "highest": 0,
  "data": "",
  "transfer": 0,
  "revoked": 0,
  "claimed": 0,
  "renewals": 0,
  "registered": false,
  "expired": false,
  "weak": false,
  "stats": {
    "bidPeriodStart": 69038,
    "bidPeriodEnd": 69758,
    "blocksUntilReveal": 619,
    "hoursUntilReveal": 103.17
  }
}
--> hsw-rpc getnameinfo btcpractice
{
  "name": "btcpractice",
  "nameHash": "2431a0223bb9a363cacddbc1505c7bb24503651cd75b34b07afbaf34970124be",
  "state": "BIDDING",
  "height": 69001,
  "renewal": 69001,
  "owner": {
    "hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "index": 4294967295
  },
  "value": 0,
  "highest": 0,
  "data": "",
  "transfer": 0,
  "revoked": 0,
  "claimed": 0,
  "renewals": 0,
  "registered": false,
  "expired": false,
  "weak": false,
  "stats": {
    "bidPeriodStart": 69038,
    "bidPeriodEnd": 69758,
    "blocksUntilReveal": 619,
    "hoursUntilReveal": 103.17
  }
}
```

I'm going to check Bob Wallet next. There might just be a UI issue that needs to be addressed in Bob Wallet

**Comment by pinheadmz** [comment] 2021-05-24 17:45
Ok I can confirm this is a UI issue in Bob Wallet as you describe - importing the second name makes data for the first name disappear. Please open an issue in https://github.com/kyokan/bob-wallet you can link back to this issue if anyone there thinks it's an underlying hsd issue ;-)

**Comment by pinheadmz** [comment] 2021-05-24 17:48
Even in Bob Wallet, the underlying hsd wallet has the correct information: 

```
--> export HSD_API_KEY=01a7e9384a2663ccb30b77cfdbf7a16bed679ba6
--> hsw-rpc selectwallet allison
null
--> hsw-rpc getbids btcpractice
[
  {
    "name": "btcpractice",
    "nameHash": "2431a0223bb9a363cacddbc1505c7bb24503651cd75b34b07afbaf34970124be",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 36
    },
    "lockup": 5110000,
    "blind": "06757269fc896b3caff0e92055bd15e14e45f15911d90b50703e6f930844b118",
    "own": false
  }
]
--> hsw-rpc getbids btcproduction
[
  {
    "name": "btcproduction",
    "nameHash": "b27dd9c0336e1db21fd0f4b8a989c3bfef4cca3ddc31b02f7b48f2c4e23d400a",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 21
    },
    "lockup": 5110000,
    "blind": "db1656bddfd25c07264f2f05407a488d28ca922518c85da414d2bff8163f054d",
    "own": false
  }
]

```

... but the UI is wrong:

<img width="871" alt="Screen Shot 2021-05-24 at 1 42 45 PM" src="https://user-images.githubusercontent.com/2084648/119387283-ba33b800-bc96-11eb-9419-a4fd8be9dde5.png">

**Comment by pinheadmz** [comment] 2021-05-24 17:55
also just wanted to verify its not just an rpc thing, the http API can retrieve both names' bids as well:

```
--> curl x:01a7e9384a2663ccb30b77cfdbf7a16bed679ba6@127.0.0.1:12039/wallet/allison/bid/btcpractice
[
  {
    "name": "btcpractice",
    "nameHash": "2431a0223bb9a363cacddbc1505c7bb24503651cd75b34b07afbaf34970124be",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 36
    },
    "lockup": 5110000,
    "blind": "06757269fc896b3caff0e92055bd15e14e45f15911d90b50703e6f930844b118",
    "own": false
  }
]
--> curl x:01a7e9384a2663ccb30b77cfdbf7a16bed679ba6@127.0.0.1:12039/wallet/allison/bid/btcproduction
[
  {
    "name": "btcproduction",
    "nameHash": "b27dd9c0336e1db21fd0f4b8a989c3bfef4cca3ddc31b02f7b48f2c4e23d400a",
    "prevout": {
      "hash": "f548f6f13e18eeb558c18bbadc1e25ffce3b82e243948a2a3e90f3fa2aad85ae",
      "index": 21
    },
    "lockup": 5110000,
    "blind": "db1656bddfd25c07264f2f05407a488d28ca922518c85da414d2bff8163f054d",
    "own": false
  }
]
```

**Comment by pinheadmz** [comment] 2021-05-24 19:54
Ok with the latest version of hsd I can reproduce this issue, my current guess is it is a new bug introduced here: https://github.com/handshake-org/hsd/pull/564/files

**Comment by pinheadmz** [comment] 2021-05-24 20:23
The offending line is here:

https://github.com/handshake-org/hsd/blob/c861e4fc95f0d023a7da4c90b93dab692b9209d0/lib/wallet/txdb.js#L2248

Funny thing about `importname` -- we trick the wallet into watching the name but since it didn't send the OPEN or any BIDs, there's no way for it to remember that it's supposed to watch that name. This normally isn't an issue but during a rescan, the wallet's namemap is cleared... and so the wallet has no idea its supposed to keep watching that name.

I can fix this bug by removing that line but the side effects will be weird and actually kinda hard to describe. The worst case scenario is, the wallet continues to watch (and save to DB) all transactions involving a name that the user was at one point interested in, but due to a reorg the auction didn't start...

**Comment by pinheadmz** [comment] 2021-05-24 20:31
potential solution:

```diff
diff --git a/lib/wallet/txdb.js b/lib/wallet/txdb.js
index c01e5add8..9d4971eb1 100644
--- a/lib/wallet/txdb.js
+++ b/lib/wallet/txdb.js
@@ -2245,7 +2245,13 @@ class TXDB {
       ns.applyState(delta);
 
       if (ns.isNull()) {
-        await this.removeNameMap(b, nameHash);
+        // Even though we are removing the namestate from the database,
+        // we are going to keep the name in the wallet's "watch list"
+        // by NOT calling removeNameMap(). This will preserve names
+        // added by rpc importname. The side effect will potential db bloat,
+        // but only in the edge case where an auction we are interested in
+        // is re-org'ed completely out of existence. In that case,
+        // we will still track the name even though the OPEN has vanished.
         b.del(layout.A.encode(nameHash));
       } else {
         b.put(layout.A.encode(nameHash), ns.encode());
diff --git a/test/wallet-importname-test.js b/test/wallet-importname-test.js
index 8ad938293..cf912fe6b 100644
```

**Comment by Anunayj** [comment] 2021-05-24 22:22
I think #499 also closes this issue.

**Closed** 2021-06-11 17:47 UTC
