### ISSUE TITLE
Assertion failed when calling sendreveal

### ISSUE THREAD

**Issue by jbroudou** [handshake-org/hsd#437] opened 2020-04-27 00:53 UTC
This assertion is failing when calling sendreveal on a name the wallet has won (there is a single bid on the name)

https://github.com/handshake-org/hsd/blob/master/lib/wallet/txdb.js#L3168

The balance of the wallet is as follows
```javascript
{
  "account": -1,
  "tx": 140,
  "coin": 25,
  "unconfirmed": 146713869,
  "confirmed": 146713869,
  "lockedUnconfirmed": 39773596,
  "lockedConfirmed": 146403625
}
```

The value of delta is 
```javascript
<Balance tx=1 coin=1 unconfirmed=-0.0211 confirmed=0.0 lockedUnconfirmed=-69.18 lockedConfirmed=0.0>
```

This is not an imported wallet and doesn't seem to affect other names in the wallet that can be revealed.

**Comment by pinheadmz** [comment] 2020-04-27 02:04
Are you running the latest master branch of hsd?

Just to be sure this isn't a duplicate of https://github.com/handshake-org/hsd/issues/381

**Comment by jbroudou** [comment] 2020-04-27 02:49
I'm running the latest release v2.1.5

https://github.com/handshake-org/hsd/releases/tag/v2.1.5

**Comment by pinheadmz** [comment] 2020-04-30 14:29
Can you check your log for more details? `~/.hsd/debug.log` should have a stack trace for the assertion error. If it doesn't, we may need to apply an unmerged patch to the logger on your node to print out stack traces. We're just going to need more details to debug this.

**Comment by pinheadmz** [comment] 2020-04-30 14:33
Are you sure the bid itself was confirmed for the name? And it's your bid? And the bid came from this wallet, this account? Have you ever rescanned this wallet?

**Comment by jbroudou** [comment] 2020-05-01 05:52
The only message in the log is


[E:2020-05-01T05:52:11Z] (node) Assertion failed.
AssertionError [ERR_ASSERTION]: Assertion failed.
    at Balance.applyTo (/home/apex/software/wallets/hsd-2.1.5/lib/wallet/txdb.js:3159:5)
    at TXDB.updateAccountBalance (/home/apex/software/wallets/hsd-2.1.5/lib/wallet/txdb.js:214:11)

The bid was confirmed and appears in the block explorer. Calling getbids confirms that the wallet placed the bid. 

```javascript
{
    "name": "legalvision",
    "nameHash": "f0acfc21132f2c4ebe743441891bf06974c807d57bc06822f9cb2255de649b98",
    "prevout": {
      "hash": "92c71e73978d5b4dd1b83c73a165ac307283e9eaf9e38d2e6cfece7b5b13f7cb",
      "index": 1
    },
    "value": 30820000,
    "lockup": 100000000,
    "blind": "8d245fdcd7acb3c1b9b5b0d0ad0cfa3d5eefbf289c9677d8bf86476ef95e091b",
    "own": true
  }
```

Performing a rescan doesn't solve the problem.

**Comment by jbroudou** [comment] 2020-05-01 07:06
Ok, seeing as the REVEAL period ends in a couple of days I commented out the assert and issued a sendreveal, which in hindsight was a bad idea. 

Although the REVEAL appears in the explorer, it does not appear when issuing a getreveals
https://hnscan.com/name/legalvision 

Issuing a second sendreveal results in the error "Could not resolve preferred inputs."

**Comment by pinheadmz** [comment] 2020-05-01 11:43
Ok this wallet may be in a corrupted state (especially after forcing the reveal).
But thats ok, I'm glad you got the reveal confirmed somehow.

At this point, I'd recommend creating a new wallet, importing your seed, and rescanning:

https://hsd-dev.org/api-docs/#create-a-wallet

Do not try to erase your old wallet or delete any files from the data directory. After this is complete I'm curious how the balances and TX histories of the two wallets compare.

Also let me know if your wallet is "very busy" -- as in, there is a block confirming more than ten TXs from your wallet all at once.

**Comment by jbroudou** [comment] 2020-05-04 01:17
So the situation seems to be deteriorating further. I've created a new wallet using the same seed and have performed a rescan from block height 0. When I attempt to get the balance of the newly created wallet I get the error `Number exceeds 2^53-1 (offset=32).`

I have several wallets in the same data directory and they now all get the same error when I try to retrieve balances.

When I start the node I see many errors along the lines of

`Verification failure: txn-already-known`

I've attempted to recreate the first wallet when starting the node using a different data directory, however after performing a rescan I only get a few of the total names that should be attached to this wallet.

**Comment by pinheadmz** [comment] 2020-05-18 12:55
This is a bit confusing, I want you to try a completely clean run of hsd so we can isolate variables.

First make sure you have cloned master branch from this repo. Launch hsd with a clean datadir:

```
$ hsd --prefix=<path/to/empty/dir>
```

Let the chain sync to 100%.

Import your wallet again:

```
$ hsw-cli mkwallet --id=test1 --mnemonic='word word word word ...'
```

Rescan from genesis:

```
$ hsw-cli --id=test1 rescan 0
```

Check the details:

```
$ hsw-cli --id=test1 balance
$ hsw-cli --id=test1 history
$ hsw-rpc selectwallet test1
$ hsw-rpc getnames
```

And see if anything looks amiss. Try to `rpc sendreveal` or `rpc sendredeem` and if there's an assertion error, paste the stack trace in this issue and STOP. We can try to debug from there, but don't make any further modifications to the code.

You said you had several wallets. If you have time, I'd actually like you to repeat this process for each wallet. One corrupt wallet could be preventing the `WalletDB` module from processing blocks entirely and corrupting other wallets in the DB.

**Comment by pinheadmz** [comment] 2020-08-03 15:55
@jbroudou any progress on this? Like I said this issue should have been fixed already. I'm going to close due to inactivity but if you still have problems please feel free to add more comments here.

**Closed by pinheadmz** 2020-08-03 15:55 UTC
