### ISSUE TITLE
Error during Download and install hsd

### ISSUE THREAD

**Issue by pkrasam** [handshake-org/hsd#28] opened 2018-08-03 05:09 UTC
Erroring out at this installation step.

**Command**
$ npm install --production

**Error**
> node-gyp rebuild

  CXX(target) Release/obj.target/unbound/src/node_unbound.o
../src/node_unbound.cc:1:10: fatal error: 'unbound.h' file not found
#include <unbound.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/unbound/src/node_unbound.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pk/Documents/code/handshake/hsd/node_modules/unbound
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by dylanbathurst** [comment] 2018-08-03 06:48
I had a similar issue when trying to `npm install` using node v8.0.0. I bumped it up v10.1.0 and was able to install successfully.

**Comment by chjj** [comment] 2018-08-03 10:51
Hmm, unbound is an optional dependency. Is the build failing completely?

**Comment by grimmy** [comment] 2018-08-03 20:10
i installed `libunbound-dev` on debian and it worked fine then.

**Comment by kargakis** [comment] 2018-08-04 21:28
> Hmm, unbound is an optional dependency. Is the build failing completely?

It seems that the executable is created but I am unable to run it.

```console
$ ./bin/hsd
Bindings for bcrypto were not built.
Please build them before continuing.
```

**Comment by kargakis** [comment] 2018-08-04 22:07
```
npm install bcrypto https://github.com/cryptocoinjs/secp256k1-node
```
fixes the above error and gets me through to a different error:
```
/opt/hsd/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/opt/hsd/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/opt/hsd/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/opt/hsd/node_modules/leveldown/leveldown.js:3:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by kargakis** [comment] 2018-08-04 22:16
I've created a Dockerfile with an earlier node version and got hsd to run, fyi https://github.com/handshake-org/hsd/pull/32

Unfortunately I couldn't install libunbound-dev with the base I used so I left it out.

**Comment by boymanjor** [comment] 2018-09-26 23:55
@pkrasam are we good to close this issue?

**Comment by tynes** [comment] 2019-03-22 23:20
@pkrasam Closing due to inactivity. Please feel free to reopen.

Try using Node.js v10 and be sure to have `libunbound-dev` installed

**Closed by tynes** 2019-03-22 23:20 UTC

**Comment by patchlog** [comment] 2019-09-18 09:20
I can't build this on macOS Mojave with node 12.10.0. I get the following errors:
`npm install --production

> unbound@0.3.4 install /Users/mihai/hsd/node_modules/unbound
> node-gyp rebuild

  CXX(target) Release/obj.target/unbound/src/node_unbound.o
../src/node_unbound.cc:82:75: error: too few arguments to function call, single argument 'context' was not specified
  target->Set(Nan::New("NodeUnbound").ToLocalChecked(), ctor->GetFunction());
                                                        ~~~~~~~~~~~~~~~~~ ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:5961:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/node_unbound.cc:517:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
      items->Set(i, Nan::CopyBuffer(data, len).ToLocalChecked());
             ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:524:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(0, Nan::New<v8::String>(result->qname).ToLocalChecked());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:526:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(0, Nan::Null());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:528:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(1, Nan::New<v8::Uint32>((uint32_t)result->qtype));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:529:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(2, Nan::New<v8::Uint32>((uint32_t)result->qclass));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:530:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(3, items);
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:533:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(4, Nan::New<v8::String>(result->canonname).ToLocalChecked());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:535:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(4, Nan::Null());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:537:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(5, Nan::New<v8::Uint32>((uint32_t)result->rcode));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:540:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(6, Nan::CopyBuffer(pkt, pkt_len).ToLocalChecked());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:542:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(6, Nan::Null());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:544:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(7, Nan::New<v8::Boolean>((bool)result->havedata));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:545:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(8, Nan::New<v8::Boolean>((bool)result->nxdomain));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:546:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(9, Nan::New<v8::Boolean>((bool)result->secure));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:547:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(10, Nan::New<v8::Boolean>((bool)result->bogus));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:550:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(11, Nan::New<v8::String>(result->why_bogus).ToLocalChecked());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:552:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ret->Set(11, Nan::Null());
         ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:556:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(12, Nan::New<v8::Boolean>((bool)result->was_ratelimited));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/node_unbound.cc:561:8: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  ret->Set(13, Nan::New<v8::Uint32>((uint32_t)result->ttl));
       ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/mihai/Library/Caches/node-gyp/12.10.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
19 warnings and 1 error generated.
make: *** [Release/obj.target/unbound/src/node_unbound.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mihai/hsd/node_modules/unbound
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unbound@0.3.4 (node_modules/unbound):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unbound@0.3.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1`

**Comment by tynes** [comment] 2019-09-18 19:48
@patchlog - There is currently a problem with [bcrypto](https://github.com/bcoin-org/bcrypto) on OSX with Node v12. I can confirm it works on Linux with Node v12. If you downgrade to Node v10 it should work fine on OSX.
